### ISSUE TITLE
Things displayed state

### ISSUE THREAD

**Issue by burdettadam** [Picolab/Manifold#13] opened 2017-08-17 19:50 UTC
things, gui state information will be stored in the individual pico with a cash in the manifold pico. 
manifold web app will update thing picos directly. the thing pico will then send events to the manifold pico to update a cash of information. While most information will be stored in the thing pico, specific app data will only persist in manifold pico, for example, tile position.

**Comment by cgrimm013** [comment] 2017-11-14 19:38
Duplicate of #10

**Closed as completed** 2017-11-14 19:38 UTC
Labels: duplicate, 4 - Done
